---
name: Test roles and modules
on: [push, pull_request_target]

jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        eda_server_version:
          - 93ef155accc3013f82a4870569638e7e1eaf2adc
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      eda_server_version: ${{ matrix.eda_server_version }}
      gh_ref: ${{ github.event.pull_request.head.sha || github.sha }}
